Models/Alumno.cs
using System;
using System.Collections.Generic;

namespace Platzi_Practica.Models
{
    public class Alumno: ObjetoEscuelaBase
    {
        public List<Evaluación> Evaluaciones { get; set; } = new List<Evaluación>();
    }
}

Models/AlumnoPromedio.cs
using System;
using System.Collections.Generic;

namespace Platzi_Practica.Models
{

    public class AlumnoPromedio
    {
        public float promedio;
        public string alumnoid;
        public string alumnoNombre;
    }
}

Models/Asignatura.cs
using System;

namespace Platzi_Practica.Models
{
    public class Asignatura:ObjetoEscuelaBase
    {

    }
}

Models/Curso.cs
using System;
using System.Collections.Generic;


namespace Platzi_Practica.Models
{
    public class Curso:ObjetoEscuelaBase
    {
        public TiposJornada Jornada { get; set; }
        public List<Asignatura> Asignaturas{ get; set; }
        public List<Alumno> Alumnos{ get; set; }

        public string Dirección { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace Platzi_Practica.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Escuela.cs
using System;
using System.Collections.Generic;


namespace Platzi_Practica.Models
{
    public class Escuela : ObjetoEscuelaBase
    {
        public int AñoDeCreación { get; set; }
        public string Pais { get; set; }
        public string Ciudad { get; set; }
        public string Dirección { get; set; }

        public TiposEscuela TipoEscuela { get; set; }
        public List<Curso> Cursos { get; set; }

        public Escuela(string nombre, int año) => (Nombre, AñoDeCreación) = (nombre, año);

        public Escuela(string nombre, int año, TiposEscuela tipo, string pais = "", string ciudad = "") : base()
        {
            (Nombre, AñoDeCreación) = (nombre, año);
            Pais = pais;
            Ciudad = ciudad;
        }

        public Escuela()
        {
        }

        public override string ToString()
        {
            return $"Nombre: \"{Nombre}\", Tipo: {TipoEscuela} {System.Environment.NewLine} Pais: {Pais}, Ciudad:{Ciudad}";
        }

    }
}

Models/Evaluaciones.cs
using System;

namespace Platzi_Practica.Models
{
    public class Evaluaciones
    {
        public string UniqueId { get; private set; }
        public string Nombre { get; set; }

        public Alumno Alumno { get; set; }
        public Asignatura Asignatura  { get; set; }

        public float Nota { get; set; }

        public Evaluaciones() => UniqueId = Guid.NewGuid().ToString();
    }
}

Models/Evaluación.cs
using System;

namespace Platzi_Practica.Models
{
    public class Evaluación:ObjetoEscuelaBase
    {
        public Alumno Alumno { get; set; }
        public Asignatura Asignatura  { get; set; }

        public float Nota { get; set; }

        public override string ToString()
        {
            return $"{Nota}, {Alumno.Nombre}, {Asignatura.Nombre}";
        }
    }
}

Models/LlaveDiccionario.cs
public enum LlaveDiccionario
{
    Escuela ,
    Curso,
    Alumno,
    Asignatura,
    Evaluación
}

Models/ObjetoEscuelaBase.cs
using System;

namespace Platzi_Practica.Models
{
    public abstract class ObjetoEscuelaBase
    {
        public string UniqueId { get; set; }
        public string Nombre { get; set; }

        public ObjetoEscuelaBase()
        {

        }

        public override string ToString()
        {
            return $"{Nombre},{UniqueId}";
        }
    }
}

Models/TiposEscuela.cs
namespace Platzi_Practica.Models
{
    public enum TiposEscuela
    {
        Primaria, 
        Secundaria, 
        PreEscolar
    }
}

Models/TiposJornada.cs
namespace Platzi_Practica.Models
{
    public enum TiposJornada
    {
        Mañana, Tarde, Noche
    }
}

Controllers/AsignaturaController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Platzi_Practica.Models;

namespace Platzi_Practica.Controllers
{
    public class AsignaturaController : Controller
    {
        public IActionResult Index()
        {
            var Asignatura = new Asignatura
            {
                UniqueId = Guid.NewGuid().ToString(),
                Nombre = "Programacion",
                
             };

                ViewBag.Fecha = DateTime.Now;
                return View(Asignatura);

        }
        
    }


}

Controllers/EscuelaController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Platzi_Practica.Models;

namespace Platzi_Practica.Controllers
{
    public class EscuelaController : Controller
    {
        public IActionResult Index()
        {
            var Escuela = new Escuela();
            Escuela.AñoDeCreación = 2005;
            Escuela.UniqueId = Guid.NewGuid().ToString();
            Escuela.Nombre = "platzi School";
            Escuela.Dirección = "Santo Domingo Este # 48";
            Escuela.Pais = "Republica Domincana";
            Escuela.Ciudad = "Ensanche la Fe";
            Escuela.TipoEscuela = TiposEscuela.Secundaria;
            
            ViewBag.Probando = "mensaje desde view bag";
            return View(Escuela);
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Platzi_Practica.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Platzi_Practica.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Asignatura/Index.cshtml
@model Platzi_Practica.Models.Asignatura;
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-center">Asignatura</h1>
<br />

<div class="col-7">
    <p>@Model.Nombre</p>
       @ViewBag.Fecha;
</div>

<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active" style="height:fit-content">
            <img class="d-inline w-75 h-50" src="~/css/Imagenes/programacion.jpg" alt="Programacion">
           </div>

            <div class="carousel-item">
                <img class="d-inline w-75 h-25" src="~/css/Imagenes/matematica.jpg" alt="Matematica">
            </div>

            <div class="carousel-item">
                <img class="d-inline w-75 h-25" src="~/css/Imagenes/ciencia.jpg" alt="Ciencia">
            </div>

        </div>

        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>

Views/Escuela/Index.cshtml
@model Platzi_Practica.Models.Escuela;
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-center">Platzi Curso</h1>
<br />

<div class="col-7">
    <h3 class="text-primary">Datos Generales Escuela</h3>
    <table class="table table-bordered border-success">
        <tbody>
            <tr>
                <th class="alert-info" scope="row">Direccion</th>
                <td>@Model.Dirección</td>
            </tr>

            <tr>
                <th class="alert-info" scope="row">Pais</th>
                <td>@Model.Pais</td>
            </tr>

            <tr>
                <th class="alert-info" scope="row">Ciudad</th>
                <td>@Model.Ciudad</td>
            </tr>

            <tr>
                <th class="alert-info" scope="row">Tipo de escuela</th>
                <td>@Model.TipoEscuela</td>
            </tr>

        </tbody>
    </table>
</div>

@ViewBag.Probando

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Platzi_Practica</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Platzi_Practica</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Escuela" asp-action="Index">Escuela</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Platzi_Practica - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>